module.exports = "A lightweight CLI that helps you manage todos."
        + "\n" + ""
        + "\n" + "todo                                                  List all todos"
        + "\n" + "todo 'This is something that I need to remember'      Creates a new todo"
        + "\n" + "todo close 1                                          Closes todo 1"
        + "\n" + "todo close all                                        Closes all todos"
        + "\n" + "todo reopen 1,2,3                                     Reopens todos 1, 2 and 3"
        + "\n" + "todo reopen all                                       Reopen all todos"
        + "\n" + "todo closed                                           Lists closed todos"
        + "\n" + "todo list                                             Lists both opened and closed todos."
        + "\n" + "todo clear                                            Deletes all todos and the storage file"
        + "\n" + "todo help                                             Prints this help.";