module.exports = "A lightweight CLI that helps you manage todos."
        + "\n" + ""
        + "\n" + "usage: todo [command]"
        + "\n" + ""
        + "\n" + "[command]"
        + "\n" + "  create <todo>               Creates a new todo. Example: `todo create \"Fix signup form validation.\"`"
        + "\n" + "  close <id_1,id_2,id_3...>   Closes todo(s)."
        + "\n" + "  close all                   Marks all todos as closed"
        + "\n" + "  reopen <id_1,id_2,id_3...>  Reopens todo(s)."
        + "\n" + "  reopen all                  Reopens all todos"
        + "\n" + "  closed                      Lists closed todos."
        + "\n" + "  opened                      Lists opened todos."
        + "\n" + "  list                        Lists both opened and closed todos."
        + "\n" + "  clear                       Deletes all todos and the storage file"
        + "\n" + "  help                        Prints this help.";